version: "3.9" # optional since v1.27.0
services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3001:3001" # dev server port
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:13.4-alpine
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5555:5432"

volumes:
  data:
